### ISSUE TITLE
add parallel computing issue

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/PEPR_example_workflow#1]
Can we add the issue about parallel computing here?

https://github.com/erikarasnick/PEPR_example_workflow/blob/2d57373b3c08e6229ba763efd5f7d9eaf416ac7d/example_workflow.Rmd#L66

We can link to the workaround https://github.com/cole-brokamp/DeGAUSS/wiki/Microsoft-Windows-Problems-and-Workarounds#parallel-computing-on-windows

It would be awesome to have a screen shot of this option, like the windows equivalent of the image below from the macOS preferences:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/4367617/62231565-496d2e80-b392-11e9-88f0-53ce3eca2eda.png">

**Comment by erikarasnick** [comment]
done
